language: node_js

script: npm run build

deploy:
  provider: pages
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false

  on:
    branch: source
