title: Gianluca Costa's Creations
description: Website of code & poetry
url: http://gianlucacosta.info

baseurl: ""

author:
  name: Gianluca Costa
  email: gianluca@gianlucacosta.info
  url: http://gianlucacosta.info

markdown: kramdown

kramdown:
 input: GFM
 syntax_highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-redirect-from

source: .
destination: ./_site
permalink: /:title
paginate: 7
paginate_path: /page:num/

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
