title: Gianluca Costa's Creations
description: Website of technology & humanism
url: https://gianlucacosta.info

baseurl: ""

author:
  name: Gianluca Costa
  email: gianluca@gianlucacosta.info
  url: https://gianlucacosta.info

motto: "Elegance always matters"

markdown: kramdown

kramdown:
 input: GFM
 syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

source: .
destination: ./_site
permalink: /blog/:title

paginate: 7
paginate_path: /blog/page:num

encoding: utf-8

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
