# Site settings
title: "Gianluca Costa's Creations"
description: "Gianluca Costa - Code & Poetry"
url: "http://gianlucacosta.info"
author:
  name: "Gianluca Costa"
  email: "gianluca@gianlucacosta.info"
  url: "http://gianlucacosta.info"

# Build settings
baseurl: /
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]

source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "9.0"
motto: "Elegance always matters"

# Options
custom_header: true
custom_nav_footer: true
reverse: true
